baseURL = "https://recipesbook.netlify.com/"
languageCode = "en-us"
title = "Willsie Family Recipe Book"
theme = "recipes"

[params]
  author = "Willsie Digital"
  description = "The Willsie Family Recipe Book that is free and open to the public"